- name: configure nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: app pre-req
  ansible.builtin.include_tasks: "app-prereq.yml"
  when: schema_load

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: install nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: systemd setup
  ansible.builtin.include_tasks: "systemd.yml"
  when: schema_load

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load